from flask import Blueprint
from flask import request
from flask import jsonify
from flask import send_file

import os
from pathlib import Path

from services.message_detector.services.batch_service import (
    analyze_uploaded_dataset
)


batch_bp = Blueprint(
    "batch",
    __name__
)


# ==========================================
# Analyze Uploaded Dataset
# ==========================================

@batch_bp.route(
    "/analyze-dataset",
    methods=["POST"]
)
def analyze_dataset():

    try:

        if "file" not in request.files:

            return jsonify({

                "error": "No file uploaded."

            }), 400


        file = request.files["file"]


        if file.filename == "":

            return jsonify({

                "error": "No file selected."

            }), 400


        # ==========================================
        # Upload Folder
        # ==========================================

        upload_folder = (
            Path(__file__).resolve().parent.parent
            / "uploads"
        )

        upload_folder.mkdir(
            parents=True,
            exist_ok=True
        )


        file_path = (
            upload_folder
            / file.filename
        )


        file.save(
            file_path
        )


        # ==========================================
        # Run Batch Analysis
        # ==========================================

        result = analyze_uploaded_dataset(
            str(file_path)
        )


        # ==========================================
        # Return Batch Result
        # ==========================================

        return jsonify({

            "file_name":
                result["file_name"],

            "total_messages":
                result["total_messages"],

            "successful_analyses":
                result["successful_analyses"],

            "results":
                result["results"],

            # IMPORTANT:
            # This must match the actual file
            # generated by batch_service.py.
            "download_file":
                result["download_file"],

            "csv_file":
                result.get(
                    "csv_file",
                    ""
                )

        })


    except Exception as e:

        print(
            "Batch analysis error:",
            e
        )

        return jsonify({

            "error": str(e)

        }), 500


# ==========================================
# Download Generated Excel Report
# ==========================================

@batch_bp.route(
    "/download/<path:filename>",
    methods=["GET"]
)
def download_dataset(filename):

    # ==========================================
    # Same output folder used by batch_service.py
    # ==========================================

    output_folder = (
        Path(__file__).resolve().parent.parent
        / "outputs"
    )


    file_path = (
        output_folder
        / filename
    )


    print(
        f"[DOWNLOAD] Requested file: {filename}"
    )

    print(
        f"[DOWNLOAD] Looking for file: {file_path}"
    )


    # ==========================================
    # Check File Exists
    # ==========================================

    if not file_path.exists():

        print(
            "[DOWNLOAD] File not found."
        )

        return jsonify({

            "error": "File not found."

        }), 404


    # ==========================================
    # Send File
    # ==========================================

    print(
        "[DOWNLOAD] File found. Sending..."
    )


    return send_file(

        str(file_path),

        as_attachment=True,

        download_name=filename

    )